In [1]:
import pandas as pd 

## Importing Data

In [2]:
df = pd.read_csv('data.csv.csv')

In [3]:
df.head()

fever  bodyPain  age  diffBreath  runnyNose  infectionProb
0  101.953688         0   99           1          1              1
1  100.094624         0  100           1          1              0
2   98.623474         0   44          -1          1              1
3  100.725960         1   64          -1          1              0
4   98.858438         1   32           1          0              0

In [4]:
df.tail()


fever  bodyPain  age  diffBreath  runnyNose  infectionProb
5694  101.742727         1   61           0          1              0
5695   99.248240         1   54           1          1              0
5696  100.103951         1   59           1          0              0
5697  100.252281         1   23           0          0              1
5698  101.211420         1   35          -1          0              1

In [5]:
df['diffBreath'].value_counts()

 1    1973
 0    1865
-1    1861
Name: diffBreath, dtype: int64

In [6]:
df.describe()

fever     bodyPain          age   diffBreath    runnyNose  \
count  5699.000000  5699.000000  5699.000000  5699.000000  5699.000000   
mean     99.972971     0.503422    50.535006     0.019653     0.501667   
std       1.147972     0.500032    28.878772     0.820050     0.500041   
min      98.000130     0.000000     1.000000    -1.000000     0.000000   
25%      98.996338     0.000000    26.000000    -1.000000     0.000000   
50%      99.954217     1.000000    50.000000     0.000000     1.000000   
75%     100.957012     1.000000    76.000000     1.000000     1.000000   
max     101.999319     1.000000   100.000000     1.000000     1.000000   

       infectionProb  
count    5699.000000  
mean        0.499386  
std         0.500043  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

## Train test splitting

In [7]:
import numpy as np

In [8]:
 def dataSplit(data,ratio):
        shffled = np.random.permutation(len(data))
        testSize = int(len(data) * ratio)
        test_indices = shffled[:testSize]
        train_indices = shffled[testSize:]
        return data.iloc[train_indices],data.iloc[test_indices]
        

In [9]:
np.random.permutation(10)

array([0, 7, 8, 6, 3, 1, 4, 2, 5, 9])

In [10]:
train, test = dataSplit(df,0.2)

In [11]:
print(train)

           fever  bodyPain  age  diffBreath  runnyNose  infectionProb
4484  101.529155         1   48           0          0              1
2775  101.220715         1   59           1          1              0
5323   99.820235         0   58           0          0              1
2949   98.748119         0   29           1          0              1
5526   99.894272         0   90           0          0              0
...          ...       ...  ...         ...        ...            ...
504    99.775081         0   18           0          0              0
4113   99.133592         1   13           1          0              1
661   101.337232         0   53           1          0              1
3380   98.769330         0   73           1          0              0
1065  100.292547         0   70           1          0              1

[4560 rows x 6 columns]


In [12]:
X_train = train[['fever','bodyPain','age','diffBreath','runnyNose']].to_numpy()
X_test = test[['fever','bodyPain','age','diffBreath','runnyNose']].to_numpy()

In [13]:
X_train

array([[101.5291549 ,   1.        ,  48.        ,   0.        ,
          0.        ],
       [101.2207152 ,   1.        ,  59.        ,   1.        ,
          1.        ],
       [ 99.82023548,   0.        ,  58.        ,   0.        ,
          0.        ],
       ...,
       [101.3372324 ,   0.        ,  53.        ,   1.        ,
          0.        ],
       [ 98.76932995,   0.        ,  73.        ,   1.        ,
          0.        ],
       [100.2925473 ,   0.        ,  70.        ,   1.        ,
          0.        ]])

In [14]:
train

fever  bodyPain  age  diffBreath  runnyNose  infectionProb
4484  101.529155         1   48           0          0              1
2775  101.220715         1   59           1          1              0
5323   99.820235         0   58           0          0              1
2949   98.748119         0   29           1          0              1
5526   99.894272         0   90           0          0              0
...          ...       ...  ...         ...        ...            ...
504    99.775081         0   18           0          0              0
4113   99.133592         1   13           1          0              1
661   101.337232         0   53           1          0              1
3380   98.769330         0   73           1          0              0
1065  100.292547         0   70           1          0              1

[4560 rows x 6 columns]

In [15]:
test

fever  bodyPain  age  diffBreath  runnyNose  infectionProb
5003   98.947063         1    4          -1          0              0
3771  100.569945         1   43           0          0              1
3726  101.926958         1   60           0          0              0
3016   99.223782         1   35           0          1              1
4853  101.879646         1   79           0          1              0
...          ...       ...  ...         ...        ...            ...
5678  101.633361         0    3           1          1              1
3656   99.282355         0   59           0          1              1
2940   99.515574         0   51           1          1              0
5055  100.149426         1   31           1          0              1
2238  100.068522         0   42           1          0              0

[1139 rows x 6 columns]

In [16]:
X_train

array([[101.5291549 ,   1.        ,  48.        ,   0.        ,
          0.        ],
       [101.2207152 ,   1.        ,  59.        ,   1.        ,
          1.        ],
       [ 99.82023548,   0.        ,  58.        ,   0.        ,
          0.        ],
       ...,
       [101.3372324 ,   0.        ,  53.        ,   1.        ,
          0.        ],
       [ 98.76932995,   0.        ,  73.        ,   1.        ,
          0.        ],
       [100.2925473 ,   0.        ,  70.        ,   1.        ,
          0.        ]])

In [17]:
Y_train = train[['infectionProb']].to_numpy().reshape(4560,)
Y_test = test[['infectionProb']].to_numpy().reshape(1139,)

In [18]:
Y_test

array([0, 1, 0, ..., 0, 1, 0], dtype=int64)

In [19]:
from sklearn.linear_model import LogisticRegression

In [20]:
clf = LogisticRegression()
clf.fit(X_train,Y_train)

LogisticRegression()

In [21]:
infProb = clf.predict_proba([[100,1,22,-1,0]])[0][1]

In [22]:
 infProb

0.5061563133082625